version: "3.9"
services:
  web:
    container_name: geesome
    build: .
    command: npm run in-docker-start
    restart: always
    ports:
      - "2052:2052"
      - "2082:2082"
    depends_on:
      - ipfs
    volumes:
      - "${GEESOME_DATA}:/geesome-node/data"
      - "${GEESOME_FRONTEND_DIST}:/geesome-node/frontend/docker-dist"
    environment:
      - IPFS_PROFILE
      - DEBUG
      - SSG_RUNTIME

  client:
    image: nginx
    ports:
      - "127.0.0.1:2042:80"
    volumes:
      - "${GEESOME_FRONTEND_DIST}:/usr/share/nginx/html"

  ipfs:
    container_name: go_ipfs
    image: "ipfs/kubo:v0.21.0"
    restart: always
    environment:
      - IPFS_PROFILE
    ports:
      - "4001:4001"
      - "8080:8080"
      - "127.0.0.1:5001:5001"
    volumes:
      - "${STORAGE_STAGING}:/export"
      - "${STORAGE_DATA}:/data/ipfs"
  lotus:
    container_name: lotus
    image: "filecoin/lotus:v1.23.3"
    restart: always
    ports:
      - "127.0.0.1:1234:1234"
      - "127.0.0.1:2345:2345"
      - "127.0.0.1:3456:3456"
      - "127.0.0.1:1777:1777"
    volumes:
      - "${LOTUS_DATA}:/home/lotus_user"