#!/bin/bash

rm -rf postgres-data && docker compose -f ./test/docker-compose.yml down && docker system prune -f && docker compose -f ./test/docker-compose.yml up -d --build --force-recreate && docker logs geesome -f
