#!/usr/bin/env bash
set -euo pipefail

rm -rf \
	test/.geesome-data \
	test/.geesome-frontend \
	test/.geesome-test-output \
	test/.ipfs \
	test/.ipfs-data \
	test/.postgres-data

docker compose -f ./test/docker-compose.yml down --remove-orphans
docker compose -f ./test/docker-compose.yml up --build --force-recreate --abort-on-container-exit --exit-code-from test test
